package soa.model;
// Generated Mar 26, 2022, 5:09:20 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Medicine generated by hbm2java
 */
public class Medicine implements java.io.Serializable {

	private Integer medicineId;
	private String medicineEnglish;
	private String medicineThai;
	private Float medicinePrice;
	private String medicineDescription;
	@JsonIgnore
	private Set medicinedetails = new HashSet(0);

	public Medicine() {
	}

	public Medicine(String medicineEnglish, String medicineThai) {
		this.medicineEnglish = medicineEnglish;
		this.medicineThai = medicineThai;
	}

	public Medicine(String medicineEnglish, String medicineThai, Float medicinePrice, String medicineDescription,
			Set medicinedetails) {
		this.medicineEnglish = medicineEnglish;
		this.medicineThai = medicineThai;
		this.medicinePrice = medicinePrice;
		this.medicineDescription = medicineDescription;
		this.medicinedetails = medicinedetails;
	}

	public Integer getMedicineId() {
		return this.medicineId;
	}

	public void setMedicineId(Integer medicineId) {
		this.medicineId = medicineId;
	}

	public String getMedicineEnglish() {
		return this.medicineEnglish;
	}

	public void setMedicineEnglish(String medicineEnglish) {
		this.medicineEnglish = medicineEnglish;
	}

	public String getMedicineThai() {
		return this.medicineThai;
	}

	public void setMedicineThai(String medicineThai) {
		this.medicineThai = medicineThai;
	}

	public Float getMedicinePrice() {
		return this.medicinePrice;
	}

	public void setMedicinePrice(Float medicinePrice) {
		this.medicinePrice = medicinePrice;
	}

	public String getMedicineDescription() {
		return this.medicineDescription;
	}

	public void setMedicineDescription(String medicineDescription) {
		this.medicineDescription = medicineDescription;
	}

	public Set getMedicinedetails() {
		return this.medicinedetails;
	}

	public void setMedicinedetails(Set medicinedetails) {
		this.medicinedetails = medicinedetails;
	}

}
